stealthrocket/timecraft

internal/timemachine/wasicall/replay.go
internal/timemachine/wasicall/wasi_test.go

Applications that use hTLS couldn't be replayed. The `wasi.BytesValue` socket option value stored in the log wasn't being compared to the system call param correctly.

wasi: fix comparison of socket option values

---

.github/workflows/python.yaml
README.md
python/Makefile
python/README.md
python/download.sh

Store python.wasm and python311.zip to S3 to allow easy retrieval by users.
On CI, the python build only occurs when a change has been made to `/python/*`. If a change was made, the python artifacts are rebuilt and published to S3.
The full test suite always runs. If a change to `/python` was made in the commit, it rebuilds the python artifacts. If not, it downloads the pre-built binaries of the last commit that did.

py: upload binaries to S3 bucket

---

sdk/python/.gitignore
sdk/python/Makefile
sdk/python/README.md

This PR adds a Makefile to help publish the Python SDK to PyPi.

python: publish SDK to PyPi

---

go.mod
go.sum

This PR pulls in https://github.com/stealthrocket/net/pull/16, ensuring that name resolution in Go (and now _all_ I/O) is non-blocking.

go: non-blocking name resolution

---

Makefile

wasi-testsuite dependencies are now installed into the test virtualenv.
Previously on Linux (Ubuntu 23.04) I was getting the following error:
```
$ make wasi-testsuite
git submodule update --init --recursive -- testdata/wasi-testsuite
python3 -m pip install -r testdata/wasi-testsuite/test-runner/requirements.txt
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.
If you wish to install a non-Debian packaged Python …
```

test: don't pollute system-wide python packages

---

go.mod
go.sum

This reverts https://github.com/stealthrocket/timecraft/pull/156.
There's an interaction between the pure Go name resolver and the sandbox that's causing name resolution to fail. Let's rollback while we investigate.

Revert "Merge pull request #156 from stealthrocket/bump-net"

---

go.mod
go.sum
internal/sandbox/conn.go
internal/sandbox/socket.go

This PR modifies the packet tunnel to use `Write` instead of `WriteTo` when the underlying `*net.UDPConn` is connected to a remote address. It addresses the error that occurred since https://github.com/stealthrocket/net/pull/16 when using the pure Go resolver:
```
write udp 192.168.1.58:62835->172.16.0.0:49152: use of WriteTo with pre-connected connection
```

sandbox: use Write instead of WriteTo on connected datagram sockets

---

internal/timecraft/replay.go
profile.go

By not calling `profiling.Prepare` on the compiled module, timecraft would skip the symbolization selection, making wzprof fallback on the basic wasm name mapping.
Example with `testdata/go/htls.wasm`.
Before:
After:

profile: use profiling.Prepare

---

go.mod
go.sum
internal/sandbox/buffer.go
internal/sandbox/conn.go
internal/sandbox/network.go
internal/sandbox/socket.go
internal/sandbox/system.go

Follow up to https://github.com/stealthrocket/wasi-go/pull/77, this PR updates wasi-go and fixes the sandbox socket layer to pass the latest tests we added.
To address an issue with datagram sockets not triggering write events when created, I modified the creation of datagram sockets to always allocate the socket buffers, and also allowed socket buffers to be resized after a socket was used.
Please take a look and let me know if something should be changed.

sandbox: fix poll timeout and allow resizing socket buffers

---

internal/assert/assert.go
internal/chaos/chaos.go
internal/chaos/chaos_test.go
internal/chaos/chunk.go
internal/chaos/error.go
internal/chaos/random.go
internal/chaos/time.go
internal/chaos/time_test.go
internal/timecraft/process.go
run.go

This PR takes a first pass at implementing fault injection when running guest modules by implementing the following fault emulators:
- a low entropy random data source
- an artificial clock drift
- a partial success of read/write operations
- an error generator that triggers EIO or shutdown of sockets
The configuration is minimal right now, it's just a ratio representing the strength of errors injected into the system.
I did not introduce a lot of knobs because I don't think we know enough yet about the settings we'll want to control and the interface we'll need, the intention is that we will add this later.

run: add --chaotic mode

---

.github/workflows/python.yaml
python/README.md
python/build.sh

Provide a vanilla (no wasmedge) CPython build for restricted environments such as wzprof test suite. Hopefully, vmware will eventually publish non-wasm-opt'd builds so that we can use those instead. In the meantime this should be good enough.
Also added the workflow file itself to the the trigger list cc @Pryz

py: publish vanilla CPython build

---

go.mod
go.sum
internal/sandbox/sandbox_test.go
internal/sandbox/system.go

Implement limits introduced in https://github.com/stealthrocket/wasi-go/pull/84
This is not yet wired to the timecraft CLI, I'm just adding the feature in the sandbox library code as an incremental step because I refactored the code a bit (mainly changed the `FileTable` field not to be embedded in the `sandbox.System` type).

sandbox: add file limits

---

format/timecraft.go

Fixes #181 
I couldn't figure out why we didn't expose it, but it seems like it would be useful to have the process id displayed in the output of `timecraft get ps -o json`.

timecraft: expose process id in json and yaml output

---

.github/workflows/python.yaml

Need to run the Python build on any file in /python, not just the subdirectory (I believe this is why the build didn't run on https://github.com/stealthrocket/timecraft/pull/187).

ci: fix glob pattern for python build trigger

---

internal/sandbox/dirfs_unix.go
internal/sandbox/fs.go
internal/sandbox/fspath/fspath.go
internal/sandbox/fspath/fspath_test.go
internal/sandbox/rootfs.go
internal/sandbox/tarfs/dir.go
internal/sandbox/tarfs/tarfs.go

Follow up to #192, this PR moves the functions that were in `internal/sandbox/path.go` to a package at `internal/sandbox/fspath` to allow reusing them in other `sandbox.FileSystem` implementations.

sandbox: move path functions to fspath package

---

internal/sandbox/tarfs/dir.go
internal/sandbox/tarfs/file.go
internal/sandbox/tarfs/placeholder.go
internal/sandbox/tarfs/symlink.go
internal/sandbox/tarfs/tarfs.go

This PR is a small optimization to reduce the memory footprint of tar file systems, instead of storing the file names, we can recompute them when opening files. This means that we only use memory to hold this field for open files instead of doing it for all files in the file system.
This yields a 23% reduction in the memory footprint needed to load alpine 3.18.2:
```
=== RUN   TestAlpine
tarfs_test.go:77: Size     = 5577728
tarfs_test.go:78: Memsize  = 108909 (1.83%)
tarfs_test.go:79: Filesize = 5290340 (94.85%)
```
```
=== RUN   TestAlpine
tarfs_test.go:77: Size     = 5577728
tarfs_test.go:78: Memsize  = 90935 (1.51%)
tarfs_test.go:79: Filesize = 5290340 (94.85%)
```

tarfs: do not store file names

---

internal/sandbox/tarfs/dir.go
internal/sandbox/tarfs/file.go
internal/sandbox/tarfs/placeholder.go
internal/sandbox/tarfs/symlink.go
internal/sandbox/tarfs/tarfs.go

Based on #195, this PR reduces the memory footprint by storing only the relevant file metadata for each file type:
- do not store the uid/gid since we don't have a use case for it, when we do it will probably make more sense to set the values to something that look like the files belong to the current process since the rootfs we create is intended to be accessible
- store the times as a count of nanosecond instead of a timespec, which halves the amount of memory needed to store hold the times
- only store sizes for regular files since directories and symlinks do not have data on disk
The change yields a 36% reduction from the parent branch, for a total of 47% from the original implementation.
```
=== RUN   TestAlpine
tarfs_test.go:77: Size     = 5577728
tarfs_test.go:78: Memsize  = 90935 …
```

tarfs: reduce the size of file stats

---

internal/sandbox/fspath/fspath.go
internal/sandbox/fspath/fspath_test.go
internal/sandbox/ocifs/ocifs.go
internal/sandbox/rootfs.go
internal/sandbox/tarfs/tarfs.go

Opening the root directory of file systems is a common operation since all path resolution needs to start at the root. The current implementations were always opening the root twice: once to start path resolution, and once because the target of path resolution was the root itself.
This PR modifies the file systems to take a shortcut: when the file being opened is the root directory, return it immediately instead of entering the path resolution stage.

sandbox: use fast path to open root directories

---

internal/sandbox/dirfs.go
internal/sandbox/dirfs_test.go
internal/sandbox/dirfs_unix.go
internal/sandbox/ocifs/file.go
internal/sandbox/ocifs/ocifs.go
internal/sandbox/rootfs.go

Based on #206, this PR modifies the `sandbox.DirFS` implementation to become a root file system (one that the guest cannot escape by referencing the root's parent directory).
The change is done by reusing `sandbox.ResolvePath` for all path resolutions instead of letting the kernel handle it.
Consequently, existing wasm modules spawned by timecraft will now be sandboxed to the preopen directories, incapable of navigating the rest of the host file system. It will keep everything the same for use cases where we mount the host root file system.

sandbox: make DirFS a root file system

---

internal/sandbox/dirfs_unix.go
internal/sandbox/fs.go

This PR modifies the `DirFS` implementation to be safe for use by multiple goroutines. While this is not strictly necessary for the WASI use case, @Pryz mentioned he wanted to look at integrating this with #183, and all other `sandbox.FileSystem` implementation are safe for concurrent use, and it is likely an assumption of anyone using a file system that concurrent access are safe.
Concurrency-safety is achieved by acquiring a reference to the file before performing any operations. After acquiring a reference, we check if the file has been closed (its `once` value is not zero). If that is the case, we mask the file descriptor, which might still be valid, but should not be used anymore. The only valid use of a file descriptor on a closed file is duplicating it during path lookups of parent …

sandbox: concurrent-safe dirfs

---

internal/sandbox/dirfs_unix.go
internal/sandbox/flags.go
internal/sandbox/fs.go
internal/sandbox/ocifs/file.go
internal/sandbox/sandboxtest/fs_rename.go
internal/sandbox/syscall_darwin.go
internal/sandbox/syscall_linux.go
internal/sandbox/syscall_unix.go
internal/sandbox/tarfs/dir.go
internal/sandbox/tarfs/tarfs.go
internal/sandbox/wasi.go

This PR adds support for passing flags to `sandbox.File.Rename`, which is necessary to implement a copy-on-write file system: RENAME_NOREPLACE ensures that we can coordinate concurrent operations creating files in the write layer of the file system.

sandbox: support rename flags

---

internal/sandbox/fs.go
internal/sandbox/subfs.go
internal/sandbox/subfs_test.go
internal/sandbox/syscall_unix.go

This PR adds an implementation of `sandbox.FileSystem`, which exposes a file system at a sub-path.
The intent is to use this as a building block to create read-write mount points in a read-only file system; the base OCI layers will be read-only, and the upper layers can be composed of `SubFS` instances that mount the writable file systems at the mount locations.
I will follow up with two more PRs before working on the integration:
- a read-only opaque file system that only contains a `.wh..wh..opq` file to hide all files underneath; this will be necessary so that files that exist in the lower layers do not appear in the mount points
- allow write operations on OCI layers; this will delegate the responsibility of being read-only or read-write to the layer instead of the OCI file system …

sandbox: add sub file system

---

internal/sandbox/dirfs_unix.go
internal/sandbox/fs.go
internal/sandbox/ocifs/file.go
internal/sandbox/ocifs/ocifs.go
internal/sandbox/ocifs/ocifs_test.go
internal/sandbox/subfs.go

Following up on #229, this PR makes the OCI layered file system writable if the underlying layers can be written. This allows the application to mutate the content of file systems mounted at specific locations with `sandbox.SubFS`.
While technically, this enables the use cases we're trying to implement (read-only file system + writable mount points), I'm feeling increasingly uneasy about this being somewhat of a workaround for the lack of a more general-purpose copy-on-write mechanism; I'm hoping we'll find the time to get back to working on this at some point: this model only works if the mount points are made opaque (e.g. masking files from layers below) because otherwise the application may end up in very strange situations where it can create directory entries in the writable layer …

ocifs: read-write layers
